export const WA = "https://api.whatsapp.com/send?phone=50689980112&text=Hola%2C%20ocupo%20consulta";
export const TEL = "+50689980112";
export const EMAIL = "jriveracheves@gmail.com";

export const RC_CASES = [
  {
    slug: "nadia-peraza",
    year: "2024",
    location: "Heredia · Costa Rica",
    status: "Sentencia firme",
    statusTone: "closed" as const,
    name: "Nadia Peraza Espinoza",
    short: "El caso más mediático de Costa Rica en años recientes. Sentencia condenatoria de 79 años — pena máxima.",
    role: "Representación de la familia",
    sentence: "79 años de prisión",
    headline: "El caso que detuvo al país",
    summary: "Representación a la familia de Nadia Peraza Espinoza en uno de los procesos penales más seguidos por la opinión pública costarricense. El responsable del femicidio fue condenado a 79 años de prisión — la pena máxima aplicable bajo el ordenamiento jurídico costarricense.",
    media: "joseph10.jpg",
    tags: ["Femicidio", "Pena máxima", "Cobertura nacional"],
    timeline: [
      { date: "2024 · Marzo",    label: "Hechos",            text: "Desaparición y posterior hallazgo de Nadia Peraza Espinoza en Heredia, Costa Rica." },
      { date: "2024 · Abril",    label: "Asunción del caso", text: "El Lic. Rivera Cheves asume la representación legal de la familia ante el Ministerio Público." },
      { date: "2024 · Octubre",  label: "Juicio oral",       text: "Inicio del juicio oral y público. Cobertura televisiva y digital en todos los medios nacionales." },
      { date: "2024 · Diciembre",label: "Sentencia",         text: "El tribunal dicta condena de 79 años de prisión — la pena máxima del ordenamiento jurídico costarricense." },
    ],
    quote: "Por Nadia, por su hija, por todas.",
    quoteContext: "Palabras finales del Lic. Rivera Cheves en las conclusiones del juicio, virales en redes sociales.",
    press: [
      { medio: "Diario Extra", t: "Algunos jueces le tienen miedo a poner la pena máxima", u: "https://www.diarioextra.com/noticia/algunos-jueces-les-da-miedo-poner-la-pena-maxima/" },
    ],
    facts: [
      { k: "Pena impuesta",     v: "79 años" },
      { k: "Año de los hechos", v: "2024" },
      { k: "Jurisdicción",      v: "Heredia, CR" },
      { k: "Estado",            v: "Firme" },
    ],
  },
  {
    slug: "carla-stefaniak",
    year: "2018",
    location: "Escazú · Costa Rica",
    status: "Sentencia firme",
    statusTone: "closed" as const,
    name: "Carla Stefaniak",
    short: "Turista venezolana-estadounidense asesinada en un Airbnb en Escazú. Cobertura internacional.",
    role: "Representación del padre",
    sentence: "Sentencia condenatoria",
    headline: "Hito de la justicia penal costarricense en el extranjero",
    summary: "Turista venezolana-estadounidense que viajó a Costa Rica para celebrar su cumpleaños y fue encontrada sin vida en un Airbnb en Escazú. El caso tuvo cobertura mediática internacional con presencia en Telemundo, CNN en Español y medios de Estados Unidos.",
    media: "joseph7.jpg",
    tags: ["Cobertura internacional", "Telemundo", "CNN"],
    timeline: [
      { date: "2018 · Noviembre", label: "Hechos",            text: "Carla Stefaniak viaja a Costa Rica para celebrar su cumpleaños y es reportada como desaparecida tras hospedarse en un Airbnb en Escazú." },
      { date: "2018 · Diciembre", label: "Hallazgo",          text: "Las autoridades costarricenses localizan los restos. El caso adquiere relevancia mediática inmediata en Estados Unidos." },
      { date: "2019",             label: "Asunción del caso", text: "El Lic. Rivera Cheves representa al padre de Carla Stefaniak en el proceso judicial." },
      { date: "2019 · 2020",      label: "Proceso y condena", text: "Acompañamiento integral durante todo el proceso penal y consolidación de la cobertura internacional del caso." },
    ],
    quote: "El caso fue un hito en la visibilidad internacional de la justicia penal de Costa Rica y en la protección de ciudadanos extranjeros en el país.",
    quoteContext: "",
    press: [
      { medio: "Telemundo",     t: "Cobertura del caso Stefaniak en Costa Rica", u: "#" },
      { medio: "CNN en Español",t: "Reportaje sobre el proceso judicial",         u: "#" },
    ],
    facts: [
      { k: "Año de los hechos",    v: "2018" },
      { k: "Jurisdicción",         v: "Escazú, CR" },
      { k: "Nacionalidad víctima", v: "Venezolana / EE.UU." },
      { k: "Cobertura",            v: "Internacional" },
    ],
  },
  {
    slug: "junieysis-merlo",
    year: "2026",
    location: "Santa Ana · Costa Rica",
    status: "Caso activo",
    statusTone: "active" as const,
    name: "Junieysis Merlo Espinoza",
    short: "Ciudadana nicaragüense de 29 años. Caso activo, representación de la familia.",
    role: "Representación de la familia",
    sentence: "En proceso",
    headline: "Justicia para Junieysis",
    summary: "Ciudadana nicaragüense de 29 años hallada sin vida en Santa Ana, Costa Rica. El Lic. Rivera Cheves asumió la representación legal de la familia de la víctima en este caso que permanece activo al momento de publicación.",
    media: "joseph3.jpg",
    tags: ["Caso activo", "Cooperación binacional", "2026"],
    timeline: [
      { date: "2026 · Enero", label: "Hechos",            text: "Junieysis Merlo Espinoza es hallada sin vida en Santa Ana, Costa Rica." },
      { date: "2026 · Enero", label: "Asunción del caso", text: "El bufete Rivera Cheves asume la representación legal de la familia y coordina con las autoridades nicaragüenses." },
      { date: "En curso",     label: "Investigación",     text: "Trabajo activo con el Ministerio Público para esclarecer los hechos y garantizar los derechos de la familia durante el proceso." },
    ],
    quote: "Trabajamos activamente para garantizar que se haga justicia y que los derechos de la familia sean respetados durante todo el proceso judicial.",
    quoteContext: "Comunicado del bufete · 2026",
    press: [],
    facts: [
      { k: "Año de los hechos",    v: "2026" },
      { k: "Jurisdicción",         v: "Santa Ana, CR" },
      { k: "Nacionalidad víctima", v: "Nicaragüense" },
      { k: "Estado",               v: "Activo" },
    ],
  },
  {
    slug: "luany-salazar",
    year: "2019",
    location: "Costa Rica",
    status: "Resuelto",
    statusTone: "closed" as const,
    name: "Luany Valeria Salazar Zamora",
    short: "Y otros casos de violencia de género representados desde 2018.",
    role: "Representación de familias",
    sentence: "Varios procesos",
    headline: "El trabajo continuado del bufete",
    summary: "El Lic. Rivera Cheves ha representado a familias de víctimas en múltiples casos de violencia de género a lo largo de los años, incluyendo el caso de Luany Valeria Salazar Zamora y el de una joven de 16 años en 2019. Cada caso representa un compromiso personal con la justicia y con las familias que buscan que sus seres queridos sean recordados con dignidad.",
    media: "joseph4.jpg",
    tags: ["Violencia de género", "Trabajo continuado", "Múltiples procesos"],
    timeline: [
      { date: "2018",     label: "Primeros casos",      text: "El bufete inicia su trabajo continuado en representación de familias víctimas de violencia de género en Costa Rica." },
      { date: "2019",     label: "Joven de 16 años",    text: "Representación a la familia de una víctima menor de edad — proceso completo en sede penal y mediático." },
      { date: "2019 →",   label: "Caso Salazar Zamora", text: "Representación a la familia de Luany Valeria Salazar Zamora durante el proceso penal." },
      { date: "Presente", label: "Trabajo continuado",  text: "Cada año, el bufete acompaña a múltiples familias en procesos relacionados con violencia contra la mujer." },
    ],
    quote: "Cada caso representa un compromiso personal con la justicia y con las familias que buscan que sus seres queridos sean recordados con dignidad.",
    quoteContext: "Sobre el trabajo continuado del bufete",
    press: [],
    facts: [
      { k: "Casos representados", v: "Múltiples" },
      { k: "Período",             v: "2018 →" },
      { k: "Enfoque",             v: "Violencia de género" },
      { k: "Sede",                v: "Penal" },
    ],
  },
];

export const RC_AREAS = [
  { n: "01", t: "Derecho Penal y Delitos Complejos",
    d: "Homicidios, femicidios, delitos sexuales, estafas, narcotráfico, extorsión, delincuencia organizada y asociaciones ilícitas.",
    items: ["Homicidios y femicidios","Delitos sexuales","Estafas y fraudes","Narcotráfico y extorsión","Delincuencia organizada","Asociaciones ilícitas"] },
  { n: "02", t: "Lavado de Dinero y Delitos Financieros",
    d: "Asesoría especializada en lavado de activos, capitalización ilícita y legitimación de capitales para personas físicas y empresas.",
    items: ["Lavado de activos","Capitalización ilícita","Legitimación de capitales","Peculado","Delitos financieros corporativos","Análisis forense financiero"] },
  { n: "03", t: "Derecho Corporativo y Empresarial",
    d: "Constitución de sociedades, fusiones, adquisiciones, fideicomisos y optimización de estructuras corporativas.",
    items: ["Constitución de sociedades","Fusiones y adquisiciones","Registro de accionistas","Fideicomisos","Compliance corporativo","Estructuras empresariales"] },
  { n: "04", t: "Derecho Laboral",
    d: "Defensa en despidos injustificados, conciliaciones y conflictos laborales del sector privado.",
    items: ["Despidos injustificados","Conciliaciones laborales","Conflictos laborales","Derechos del trabajador","Defensa del empleador","Procesos ante el MTSS"] },
  { n: "05", t: "Derecho Notarial y Registral",
    d: "Servicios notariales y registrales: escrituras, testamentos e inscripción de actos en registros públicos.",
    items: ["Escrituras públicas","Testamentos","Inscripción registral","Autenticación de documentos","Traspasos de propiedad","Contratos notariales"] },
  { n: "06", t: "Asesoría Estratégica Internacional",
    d: "Estrategia legal frente a terrorismo, subversión y crimen organizado a nivel nacional e internacional.",
    items: ["Crimen organizado transnacional","Terrorismo y subversión","Estrategias de defensa internacional","Cooperación judicial internacional","Extradiciones","Delitos transfronterizos"] },
  { n: "07", t: "Investigaciones Criminales",
    d: "Investigación de homicidios, accidentes de tránsito y delitos financieros con equipo criminalístico y forense.",
    items: ["Investigación de homicidios","Accidentes de tránsito","Análisis criminalístico","Peritajes forenses","Análisis financiero forense","Reconstrucción de hechos"] },
];

export const RC_PRESS = [
  { medio: "Diario Extra", t: "Caso Nadia Peraza: algunos jueces le tienen miedo a poner la pena máxima", u: "https://www.diarioextra.com/noticia/algunos-jueces-les-da-miedo-poner-la-pena-maxima/", year: "2024" },
  { medio: "ElMundo.cr",   t: "Diputados derrochan mientras el pueblo con hambre",                          u: "https://elmundo.cr/opinion/diputados-derrochan-mientras-el-pueblo-con-hambre-el-cafetin-de-la-verguenza-en-la-asamblea-legislativa/", year: "2024" },
  { medio: "Delfino.cr",   t: "Concusión y dignidad institucional",                                         u: "https://delfino.cr/2025/04/concusion-y-dignidad-institucional-una-reflexion-juridica-y-ciudadana-para-costa-rica", year: "2025" },
  { medio: "ElMundo.cr",   t: "Menores de edad, mayores delitos",                                           u: "https://elmundo.cr/opinion/menores-de-edad-mayores-delitos-esta-fallando-la-justicia-penal-juvenil-en-costa-rica/", year: "2025" },
  { medio: "Delfino.cr",   t: "Caso Topo: ¿quién defiende a los jueces?",                                   u: "https://delfino.cr/2025/05/caso-topo-quien-defiende-a-los-jueces", year: "2025" },
  { medio: "CRHoy",        t: "Ley 9986: técnica jurídica y aeronáutica",                                   u: "https://crhoy.com/ley-9986-cuando-la-tecnica-juridica-y-la-tecnica-aeronautica-convergen-para-proteger-al-estado/", year: "2025" },
];

export const RC_FORMACION = [
  { t: "Máster en Compliance, Fraude y Blanqueo",  s: "EALDE Business School, España · Universidad de Murcia", d: "Doble titulación internacional con especialidad en Gestión de Riesgos y Análisis Forense Financiero." },
  { t: "Maestría en Derecho Penal",                 s: "Universidad Latina de Costa Rica · 2015",               d: "Especialización en litigación penal compleja, teoría del delito y defensa de derechos fundamentales." },
  { t: "Maestría en Derecho Notarial y Registral",  s: "Universidad Latina de Costa Rica · 2010",               d: "Gestión de escrituras públicas, testamentos e inscripción en registros públicos." },
  { t: "Licenciado en Derecho",                     s: "Universidad de la Salle · 2008",                        d: "Formación integral en todas las ramas del derecho costarricense e internacional." },
  { t: "Especialización en Litigación Oral",        s: "Temple University · 2024",                              d: "Técnicas avanzadas de oratoria forense, argumentación legal y presentación ante tribunales." },
  { t: "Especialización en Compras Públicas",       s: "Universidad de Costa Rica · 2024",                      d: "Marco normativo, estrategias en contratación administrativa y licitaciones del Estado." },
];

export const RC_EXP = [
  { anio: "2015 — presente", cargo: "Abogado litigante en materia penal",  lugar: "Bufete Rivera Cheves & Asociados",          desc: "Representación en casos penales complejos, asesoría en política penal y litigación judicial a nivel nacional e internacional." },
  { anio: "2020 — 2022",     cargo: "Asesor ad honorem",                   lugar: "Asamblea Legislativa de Costa Rica",        desc: "Asesoría jurídica especializada en materia penal y legislativa para la Asamblea Legislativa." },
  { anio: "2016 — 2018",     cargo: "Asesor legal",                        lugar: "Colegio de Ciencias Económicas de CR",      desc: "Asesoría legal institucional en materia administrativa y penal." },
  { anio: "2014 — 2015",     cargo: "Notario público de planta",           lugar: "Corporación Grupo Q",                       desc: "Gestión notarial y registral para una de las corporaciones más grandes de Centroamérica." },
  { anio: "2011 — 2012",     cargo: "Asesor legal",                        lugar: "Municipalidad de Santa Bárbara de Heredia", desc: "Asesoría en materia administrativa, contratación pública y asuntos municipales." },
  { anio: "2010 — 2011",     cargo: "Abogado de planta",                   lugar: "Banco Nacional de Costa Rica",              desc: "Asesoría legal en materia bancaria, contractual y gestión de créditos." },
  { anio: "2009 — 2010",     cargo: "Asesor legal",                        lugar: "Dirección General de Aviación Civil",       desc: "Asesoría jurídica en regulación aeronáutica y derecho administrativo." },
  { anio: "2008 — 2013",     cargo: "Abogado de Fiscalía",                 lugar: "Colegio de Abogados de Costa Rica",         desc: "Investigación y tramitación de casos disciplinarios en el Colegio de Abogados." },
];

export const RC_DOCENCIA = [
  "Universidad Santa Lucía",
  "Universidad Libre de Costa Rica (ULICORI)",
  "Universidad Panamericana",
  "Universidad Florencio del Castillo",
  "ULACIT",
  "Universidad de San José",
];
